version: '2.1'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0.3-msbuild
    hostname: affy
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore && dotnet publish -c Release -o ./obj/Docker/publish"
